const data = [
  {
    _id: "67209daf2394a4eca72b2bf8",
    id: 660,
    pid: null,
    code: "sys",
    type: 1,
    path: "660",
    order: 4,
    linkType: null,
    router: null,
    link: null,
    icon: "settings",
    iconType: 1,
    target: "self",
    isHidden: false,
    status: 1,
    name: {
      "zh-CN": "系统管理",
      "zh-HK": "系統管理",
      en: "System Management",
      ja: "システム管理",
      ko: "시스템 관리",
      ar: "إعدادات النظام",
    },
    __v: 0,
  },
  {
    _id: "67209ddf2394a4eca72b2c01",
    id: 662,
    name: {
      "zh-CN": "权限",
      "zh-HK": "權限",
      en: "Permission",
      ar: "الصلاحيات",
      ja: "権限",
      ko: "권한",
    },
    pid: 660,
    code: "sys.permission",
    type: 1,
    path: "660-662",
    order: 2,
    status: 1,
    isHidden: false,
  },
  {
    _id: "67209dee2394a4eca72b2c05",
    id: 663,
    name: {
      "zh-CN": "资源",
      "zh-HK": "資源",
      en: "Resource",
      ar: "الموارد",
      ja: "リソース",
      ko: "리소스",
    },
    pid: 662,
    code: "sys.permission.resource",
    type: 1,
    path: "660-662-663",
    order: null,
    linkType: 1,
    router: "/sys/permission/resource",
    link: "",
    target: "self",
    isHidden: false,
    status: 1,
  },
  {
    _id: "67209df72394a4eca72b2c09",
    id: 664,
    name: {
      "zh-CN": "角色",
      "zh-HK": "角色",
      en: "Role",
      ar: "المهمة",
      ja: "ロール",
      ko: "역할",
    },
    pid: 662,
    code: "sys.permission.role",
    type: 1,
    path: "660-662-664",
    order: 2,
    linkType: 1,
    router: "/sys/permission/role",
    link: "",
    target: "self",
    isHidden: false,
    status: 1,
  },
  {
    _id: "67209e402394a4eca72b2c25",
    id: 666,
    name: {
      "zh-CN": "我的",
      "zh-HK": "我的",
      en: "My",
      ar: "من",
      ja: "マイページ",
      ko: "내 정보",
    },
    pid: null,
    code: "my",
    type: 1,
    path: "666",
    order: 2,
    linkType: null,
    router: "/404",
    link: null,
    icon: "fit-center",
    iconType: 1,
    target: 1,
    isHidden: false,
    status: 1,
  },
  {
    _id: "67209e4e2394a4eca72b2c2a",
    id: 667,
    name: {
      "zh-CN": "密码和身份认证",
      "zh-HK": "密碼和身份認證",
      en: "Authentication",
      ar: "التحقق من الهوية وكلمة المرور",
      ja: "パスワードと認証",
      ko: "비밀번호 및 인증",
    },
    pid: 666,
    code: "my.authentication",
    type: 1,
    path: "666-667",
    order: null,
    linkType: 1,
    router: "/my/authentication",
    link: "",
    target: "self",
    isHidden: false,
    status: 1,
  },
  {
    _id: "67209e562394a4eca72b2c2e",
    id: 668,
    name: {
      "zh-CN": "我的资料",
      "zh-HK": "我的資料",
      en: "My Profile",
      ar: "معلوماتي",
      ja: "プロフィール",
      ko: "내 프로필",
    },
    pid: 666,
    code: "my.profile",
    type: 1,
    path: "666-668",
    order: 2,
    linkType: 1,
    router: "/my/profile",
    link: "",
    icon: "zoom-in",
    iconType: 1,
    target: "self",
    isHidden: false,
    status: 1,
  },
  {
    _id: "677f97054937d3a3b84ec258",
    id: 15,
    pid: null,
    code: "projects",
    type: 1,
    path: "15",
    order: 1,
    linkType: 1,
    router: "/wenjuan/project",
    link: "",
    icon: "menu",
    iconType: 1,
    target: "self",
    isHidden: false,
    status: 1,
    name: {
      "zh-CN": "项目",
      "zh-HK": "",
      en: "",
      ja: "",
      ko: "",
      ar: "",
    },
    __v: 0,
  },
  {
    _id: "677f9df94937d3a3b84ec3b9",
    id: 17,
    pid: 660,
    code: "sys.account",
    type: 1,
    path: "660-17",
    order: 1,
    linkType: 1,
    router: "/sys/account/accountlist",
    link: "",
    icon: "role",
    iconType: 1,
    target: "self",
    isHidden: false,
    status: 1,
    name: {
      "zh-CN": "账户",
      "zh-HK": "賬戶",
      en: "account",
      ja: "アカウント",
      ko: "계정",
      ar: "الحسابات",
    },
    __v: 0,
  },
  {
    _id: "677f9fd54937d3a3b84ec409",
    id: 18,
    pid: 660,
    code: "sys.team",
    type: 1,
    path: "660-18",
    order: 3,
    linkType: 1,
    router: "/sys/team/teamlist",
    link: "",
    icon: null,
    iconType: null,
    target: "self",
    isHidden: false,
    status: 1,
    name: {
      "zh-CN": "团队",
      "zh-HK": "團隊",
      en: "team",
      ja: "チーム",
      ko: "팀",
      ar: "فريق",
    },
    __v: 0,
  },
  {
    _id: "6784c60024271c5e3e685d2f",
    id: 21,
    pid: 15,
    code: "projects.wjmng",
    type: 2,
    path: "15-21",
    order: null,
    linkType: null,
    router: null,
    link: null,
    icon: null,
    iconType: null,
    target: null,
    isHidden: null,
    status: 1,
    name: {
      "zh-CN": "问卷管理",
      "zh-HK": "",
      en: "",
      ja: "",
      ko: "",
      ar: "",
    },
    __v: 0,
  },
];
const database = "mpadmin";
use(database);

db.resources.deleteMany({});
db.resources.insertMany(data);
console.log(data.length);
db.counters.findAndModify({
  query: { _id: "resourceid" },
  update: { $set: { seq: data.length } },
  new: true,
  upsert: true,
});
